[connections.todo_db]
type = "sql"
url = "sqlite:///todo.db"

[connections.supabase_db]
type = "sql"
url = "postgresql://postgres.azjfhqxtuqakjttlcqob:sHoqiqmawBFU5znG@aws-0-eu-west-3.pooler.supabase.com:6543/postgres"
